name: Let's Auth
description: Spiritual successor to Persona
logo: /images/logo.png

# Used for Sitemap.xml and RSS feed
url: http://letsauth.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Includes an icon in the footer for each username you enter
footer-links:
  # email: contact@letsauth.org
  github: LetsAuth
  rss: false

# Jekyll configuration

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

sass:
  style: :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Files excluded from production site
exclude:
    - LICENSE
    - README.md
    - CNAME
